### ISSUE TITLE
RAM issue - increasing > 4GB / already discussed on Test Alpha Homekit-Controller

### ISSUE THREAD

**Issue by mac89muc** [Apollon77/ioBroker.homekit-controller#266]
The RAM used by the Adapter is constantly increasing (>4 GB) while the adapter is running. After a restart of the Adapter the RAM is resetted to 0 and then increasing again.

The values at the system Datapoints memRss and both heap are showing different values than the osx system activity board.

This Topic was already discussed with @Apollon77 at the Test Alpha Homekit-Controller Forum - [here](https://forum.iobroker.net/topic/48570/test-alpha-homekit-controller-0-0-x/209?_=1676364827485)

<img width="492" alt="1667164380093-ram-2" src="https://user-images.githubusercontent.com/69312437/218834643-bb2b807f-ae5e-4faa-ae4e-5efeb4f05d71.png">

![1670920578629-memrss](https://user-images.githubusercontent.com/69312437/218834673-d5382046-7973-4e2e-a478-63002347b251.svg)

![1670920593910-memheaptotal](https://user-images.githubusercontent.com/69312437/218834688-c4260b68-c3b1-4a6e-8a11-efd78a381ba8.svg)

![1670920609936-homekit-controller-0-heap-actually-used-2](https://user-images.githubusercontent.com/69312437/218834712-05b118df-dea3-4c16-9d48-c0652ca82218.svg)

Workaround - restarting the adapter daily via restart schedule 

JS-Controller version - 4.0.24
Node.js v16.17.0 
NPM 8.15.0
macOS 10.14.6 Mojave

Any help is appreciated - regards

**Comment by Apollon77** [comment]
Please also summarize here. Ip or also ble? Is Ble activated? If yes try to disable if not needed to make sure it do not come from there. A full debug log (also running some time like 1h or such) was in Forum? If not please post here

**Comment by mac89muc** [comment]
for the moment I'm using the adapter only for bluetooth connections - ip is disabled. Log direct from the disk - one file 1h before scheduled restart and one file 1h after scheduled restart.

[1h vor restart.txt](https://github.com/Apollon77/ioBroker.homekit-controller/files/10748017/1h.vor.restart.txt)
[1h nach restart.txt](https://github.com/Apollon77/ioBroker.homekit-controller/files/10748019/1h.nach.restart.txt)

**Comment by Apollon77** [comment]
only bluetooth ... oookk ... Then I have a suspicion ... there seems to be an issue in nobile in the latest version ... we had a comparable report in ble adapter about "high CPU usage" ... but there it was seen that also one field gets longer an longer ... so we need to look into this -> https://github.com/AlCalzone/ioBroker.ble/issues/778

Bitte poste mal die Ausgabe von:

npm list @abandonware/bluetooth-hci-socket
npm list @abandonware/noble

**Comment by mac89muc** [comment]
npm list @abandonware/bluetooth-hci-socket ergibt

`iobroker.inst@3.0.0 /usr/local/iobroker
└─┬ iobroker.ble@0.13.0
  └─┬ @abandonware/noble@1.9.2-15
    └── @abandonware/bluetooth-hci-socket@0.5.3-8
`

npm list @abandonware/noble

`iobroker.inst@3.0.0 /usr/local/iobroker
├─┬ iobroker.ble@0.13.0
│ └── @abandonware/noble@1.9.2-15
└─┬ iobroker.homekit-controller@0.5.1
  └─┬ hap-controller@0.8.1
`
beides jeweils im iobroker Verzeichnis ausgeführt (bei macOS - /usr/local/iobroker)

**Comment by Apollon77** [comment]
ook, thenm first of all, UPDATE homekit-controlelr to the latest version!! you areusing completely buggy versions and we fixed that end of decekber and applied the better version >1month ago.

Please install 0.5.7, then check again

**Comment by Apollon77** [comment]
ANd also update ble adapter to latest beta 0.13.3

**Comment by mac89muc** [comment]
OK - weird no updates are shown for HomeKit-controller - is it a beta... I try to update via GitHub.

I have deactivated the ble adapter long ago because of a notice that both adapters side by side can cause errors..
I'll try to update the ble adapter

![image](https://user-images.githubusercontent.com/69312437/219204579-aaabf613-5ca3-4518-930e-457f64049038.png)

**Comment by Apollon77** [comment]
Ohh yes stilbeta ... my fault ... so please update both. Csn be done via Admin - expertmode - custom install (github icon) - choose first tab "from npm". then you always get the current beta version

**Comment by mac89muc** [comment]
Tried it with the ble adapter - dumb question how can I update the existing instance to the beta? after the update process it's still showing the regular version. if I install a second instance then there's the updated beta version but on the first instance still the regular version.

Would be annoying if I have to pair all the ble devices to the new instance when I update the HomeKit-controller..

**Comment by Apollon77** [comment]
this should not happen. try to reload UI ... else try "iob upload ble" But you also need to update homekit-controller

AFter that the npom list from above should show updated hci socket verionnnumer and also noble

**Comment by mac89muc** [comment]
Still the same - iobroker update shows

Adapter "ble" :0.13.0 installed 0.13.3


Do I have to change the repository (actual Stable)

**Comment by Apollon77** [comment]
If you have amultihost system .... doid you installed the new verison on the correct host?

**Comment by Apollon77** [comment]
and also honestly ... ble was just seen ... here we write about homekit-controller :-) was just because both use noble and such and aso both are pot affected

**Comment by mac89muc** [comment]
no multihost just a single installation.
I know it's about HomeKit-controller but it's the same with HomeKit-controller - installed version is 0.5.7 but in the instance it's showing 0.5.1.
I just want to avoid any problems so I don't have to pair my device again and in the worst case I have to adjust my scripts..

Any suggestions how I can fix the version of the installed instance to the right version (of the beta)?

**Comment by Apollon77** [comment]
Ok dann alles anders. Starte einfach den prozess nachd em update und schau ins log da steht welche version gestartet wird ... dann ist die anzeige im Admin erstmal egal

**Comment by mac89muc** [comment]
Ok, dann ist die Admin Übersicht wohl falsch angezeigt - laut Log 0.5.7 - 

`2023-02-16 11:55:08.838  - [34mdebug[39m: homekit-controller.0 (889) States create User PubSub Client
2023-02-16 11:55:08.906  - [34mdebug[39m: homekit-controller.0 (889) States connected to redis: 127.0.0.1:9000
2023-02-16 11:55:09.116  - [34mdebug[39m: homekit-controller.0 (889) Plugin sentry Initialize Plugin (enabled=true)
2023-02-16 11:55:09.458  - [32minfo[39m: homekit-controller.0 (889) starting. Version 0.5.7 (non-npm: Apollon77/ioBroker.homekit-controller) in /usr/local/iobroker/node_modules/iobroker.homekit-controller, node: v16.17.0, js-controller: 4.0.24
`

npm list @abandonware/noble ergibt - 

`iobroker.inst@3.0.0 /usr/local/iobroker
├─┬ iobroker.ble@0.13.3 (git+ssh://git@github.com/AlCalzone/ioBroker.ble.git#5e6f6a67ffbe3be6298661e369c1747bf85bc9ba)
│ └── @abandonware/noble@1.9.2-19
└─┬ iobroker.homekit-controller@0.5.7 (git+ssh://git@github.com/Apollon77/ioBroker.homekit-controller.git#c788d24ba9c12f0e09da78fc8bbdb15b9463cc5e)
  └─┬ hap-controller@0.9.2
    └── @abandonware/noble@1.9.2-19 deduped`

npm list @abandonware/bluetooth-hci-socket zeigt - 

`iobroker.inst@3.0.0 /usr/local/iobroker
└── (empty)
`
sollte wohl anderes Ergebnis liefern, oder??

Ich lösche jetzt also mal den täglichen scheduled restart des homekit-controllers und beobachte die RAM Nutzung, oder?
Den BLE Adapter kann ich weiterhin deaktiviert lassen - hat keine Auswirkung auf den Test/Funktion?

Gruß

**Comment by Apollon77** [comment]
Ahhhhhhhhh ... jeetzt ... stimmt ... ist ja ein macos ... da wird /bluetooth-hci-socketgar nicht genutzt und installiert ...ok ... dann schau mal ob es nochpassiert ... sonst muss ich da in noble reinschauen ... puhhhh

**Comment by mac89muc** [comment]
Ok - dann lösche ich den restart und schaue ob der RAM weiterhin in die Höhe schießt.. 
Danke schon mal bis hier her.

**Comment by mac89muc** [comment]
Zwischeninfo - aktuell liegt die Speichernutzung lt. macOS Aktivitätsanzeige wieder bei > 1 GB

![image](https://user-images.githubusercontent.com/69312437/219643368-58256d92-3879-412f-b7e6-42df3a9ddf8d.png)

**Comment by Apollon77** [comment]
Ok, dann müssen wir bei noble reinschauen ... yyeeaaayyy :-(

**Comment by mac89muc** [comment]
mmhhh - ich aktivier zwischenzeitlich mal wieder den scheduled restart.
RAM aktuell bei > 2 GB

![image](https://user-images.githubusercontent.com/69312437/219901408-b61fe60b-1c09-438b-b5ba-667e5973b091.png)

**Comment by Apollon77** [comment]
Ja, werde bissl zeit brauchen bis ich dazu komme, sorry

**Comment by mac89muc** [comment]
OK, wenn noch Infos benötigt werden gib Bescheid.

**Comment by Apollon77** [comment]
New noble version prepared ... needs to be releaed now ... https://github.com/abandonware/noble/pull/298 ... maybe fixes the issue

**Comment by mac89muc** [comment]
unfortunately no improvements concerning the ram - upgraded to 0.5.8 and the value increases again to more than 1,6 GB after 20 hours.

**Comment by Apollon77** [comment]
Ok, but then at least good to know that it was not about this :-( But bad because we need to look deeper and "again" :-(
